#This code doesn't contain any time limit 
from selenium import  webdriver
from selenium.webdriver.common.keys import Keys
driver=webdriver.Chrome(executable_path="C:\Driver\chromedriver_win32\chromedriver.exe")
driver.maximize_window()
driver.get("https://www.saucedemo.com/")
print(driver.title)
user_input=driver.find_element_by_name("user-name")
user_input.send_keys("standard_user")
user_pwd=driver.find_element_by_name("password")
user_pwd.send_keys("secret_sauce")
login_button=driver.find_element_by_id("login-button").click()
product=driver.find_element_by_class_name("inventory_item_name").click()
cart=driver.find_element_by_xpath("//*[@id='inventory_item_container']/div/div/div/button").click()
cartbox=driver.find_element_by_class_name("shopping_cart_container").click()
checkout=driver.find_element_by_xpath("/html/body/div/div[2]/div[3]/div/div[2]/a[2]").click()
f_name=driver.find_element_by_id("first-name")
f_name.send_keys("Shridhar")
name=driver.find_element_by_xpath("//*[@id='last-name']")
name.send_keys("Saraf")
Zip=driver.find_element_by_id("postal-code").send_keys("585103")
Continue=driver.find_element_by_xpath("//*[@id='checkout_info_container']/div/form/div[2]/input").click()
finish=driver.find_element_by_xpath("//*[@id='checkout_summary_container']/div/div[2]/div[8]/a[2]").click()
driver.quit()
